[package]
name = "ic-sqlite-vfs-kv-bench"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.20.1"
ic-sqlite-vfs = { path = "../..", default-features = false, features = ["bench-profile", "sqlite-precompiled"] }
serde = { version = "1", features = ["derive"] }
