[env]
LIBSQLITE3_FLAGS = "-DSQLITE_OS_OTHER=1 -USQLITE_THREADSAFE -DSQLITE_THREADSAFE=0 -USQLITE_ENABLE_COLUMN_METADATA -USQLITE_ENABLE_DBSTAT_VTAB -USQLITE_ENABLE_FTS3 -USQLITE_ENABLE_FTS3_PARENTHESIS -USQLITE_ENABLE_FTS5 -USQLITE_ENABLE_JSON1 -USQLITE_ENABLE_RTREE -USQLITE_ENABLE_STAT4 -USQLITE_SOUNDEX -DSQLITE_OMIT_DATETIME_FUNCS -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_OMIT_WAL -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_TEMP_STORE=3"
CC_SHELL_ESCAPED_FLAGS = "1"
CC_wasm32_unknown_unknown = { value = "scripts/wasm32-unknown-unknown-cc.sh", relative = true }
CFLAGS_wasm32_unknown_unknown = "--target=wasm32-wasip1"
